### ISSUE TITLE
Style, keyboardType and cursorColor parameters

### ISSUE THREAD

**Issue by Josua2012** [4inka/flutter_easy_autocomplete#1]
Hi,
There are no style, keyboardType and cursorColor parameters, so the font size, color, ... cannot be specified. :(
Could you put these parameters? 
Thank you so much for your awesome plugin. 
Regards,
Jose

**Comment by 4inka** [comment]
Hi, Jose
Thank you for the suggestions. They will be taken in consideration and I will add those as soon as possible

**Comment by Josua2012** [comment]
Thanks @4inka.

**Comment by 4inka** [comment]
Hello @Josua2012 
Your suggestions were very useful and are already in the new version of the package. You can find the new parameters by updating to version 1.1.0.
I hope those changes satisfy your needs.
Have a nice day

**Comment by Josua2012** [comment]
Hello @4inka,
Thank you very much, you are a crack, very fast. Now I can customize the suggestions. Fabulous. 💯 
However, if I'm not mistaken, the ability to style the text of the fieldtext is missing, the Style property found in the TextField() widget is missing.
Another question, when do you think you will be able to add the ability to asynchronous suggestions fetch? 
Again, thank you so much for your wonderful component, it works great. 
Have a nice day.

**Comment by 4inka** [comment]
I'm sorry about the TextField text style missing. Will add it as soon as possible because it's also a very important feature.
The async suggestions will be added later on this week hopefully.

**Comment by Josua2012** [comment]
Thanks for your quick responses.

**Comment by 4inka** [comment]
Hi @Josua2012 
Just uploaded a new version of the package to pub.dev with version number 1.2.0 and in that version you can find the param `inputTextStyle` that can be used to style the textfield text and also `asyncSuggestions` that can be used to substitute `suggestions` and receive data from a Future.
Hope that satisfies your current needs.

Have a nice day

**Comment by Josua2012** [comment]
Hi @4inka,

Wonderful, it now has almost all the functionality a user could want. 💯 
I don't know if it would be very complicated, but you could put a SuggestionsEx parameter that allows you to customize the list of suggestions, for example, with an icon, ...? 
It would also be very interesting to provide with the library example an example of the new parameter asyncSuggestions.

What do you think of these ideas? 

Your plugin may be the best widget autocomplete for Flutter.
Thank you very much for such a great widget. 🥇

**Comment by Josua2012** [comment]
Simply wonderful.
Many thanks.
