### ISSUE TITLE
I can't find function for when I tap a value

### ISSUE THREAD

**Issue by kassemxx1** [4inka/flutter_easy_autocomplete#12]

**Comment by 4inka** [comment]
Hello @kassemxx1 

Currently there is no function to handle the action when a user taps a suggestion.
When a value is tapped, all the actions are handled by the `onChanged` parameter the same way changes are handled when a user types something inside the field.
Unfortunately currently there is no plan to add a parameter to handle the suggestion tap events.

**Comment by kassemxx1** [comment]
if  I have a function when I use it on onChanged the function repeated  on every letter changed
