### ISSUE TITLE
[request] Validator

### ISSUE THREAD

**Issue by nio74** [4inka/flutter_easy_autocomplete#15]
Hello, How can I to implement validator in to a form?

`validator: (value) {
        if (value == null || value.isEmpty) {
          return '$_txtLable cannot be empty ';
        }
        return null;
      },
    );`

**Comment by 4inka** [comment]
Hi @nio74 

Thank you for your suggestion and sorry for the very late feedback.
I've updated the package and there's now a parameter called `validator` that lets you add validations to the field. It works as a normal TextFormField validation would work inside a form.

Have a nice day
