### ISSUE TITLE
A quick fix for a little bug

### ISSUE THREAD

**Issue by zsmiklos** [4inka/flutter_easy_autocomplete#17]
Thank you for your useful package!
I found a little bug when user type a character, lose focus then get the focus again. The circular widget appears. Fix for this case: 

```
void closeOverlay() {
    if (_hasOpenedOverlay) {
      _overlayEntry.remove();
      setState(() {
        _previousAsyncSearchText = "";  //  this line was missing
        _hasOpenedOverlay = false;
      });
    }
  }
```

**Comment by 4inka** [comment]
Hello @zsmiklos 

Thank you very much for the contribution. I've now fixed the issue and published a new version for the package.

Have a nice day
