### ISSUE TITLE
Using a controller with easy_autocomplete does not work correctly

### ISSUE THREAD

**Issue by jamolina2021** [4inka/flutter_easy_autocomplete#5]
Hello @4inka,

I am using a TextEditingController control with your plugin, but when doing the dispose it produces the following error:
"A TextEditingController was used after being disposed.
Once you have called dispose() on a TextEditingController, it can no longer be used."
The code I am using is the following: 
```
class _LoginPageState extends State<LoginPage> {
  TextEditingController _easyAutocompleteController = TextEditingController();

  @override
  void initState() {
    super.initState();
    _easyAutocompleteController.text = _prefs.lastUserSel;
    _userName = _easyAutocompleteController.text;
  }

  @override
  void dispose() {
    _easyAutocompleteController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      .....
      .....
                                  EasyAutocomplete(
                                controller: _easyAutocompleteController,
                                decoration: InputDecoration(
                                  fillColor: Colors.red,
                                  border: InputBorder.none,
                                  .....
                                  .....
```

Is it a problem with my code or is it an easy_autocomplete bug?
Thank you very much for your help.

**Comment by 4inka** [comment]
Hello @jamolina2021 

Thank you for the feedback. I was able to reproduce your issue and can confirm that was a bug related to the package.
Just published the version with the fix to pub.dev and you can try it again by updating the package version to 1.2.2.

**Comment by jamolina2021** [comment]
Many thanks. 👍
