### ISSUE TITLE
Keyboard accept button problem (android)

### ISSUE THREAD

**Issue by jamolina2021** [4inka/flutter_easy_autocomplete#9]
Hi,
I think this is a bug. In the TextField widget, if the keyboard button with the check is clicked, the keyboard is hidden, however in your EasyAutocomplete widget when I click this button the keyboard is not hidden.
Check out the following video:
https://recordit.co/V6bipT6NXj

Thank you very much for the quick resolution of the problems. You are a crack. 💯 🥇

**Comment by 4inka** [comment]
Hello @jamolina2021 

I agree with you. That shouldn't be the default behavior.
Unfortunatelly I can't handle this issue today, but I will do it tomorrow and hopefully come back with an answer.

Have a nice day

**Comment by jamolina2021** [comment]
Hi @4inka 
Now it works wonderfully. 👍 
Again, thank you very much for your quick resolution of the issues.
Have a nice day!
